import Providers from '@/components/providers/providers';
import '@/styles/index.scss';
import type { Metadata } from "next";

// $======================== RootLayout ========================$ //

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className='wrapper'>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
